### ISSUE TITLE
thanks you!

### ISSUE THREAD

**Issue by oriwideops** [enishant/tinyurl#1]
I was searching for an API, and I came across this.
It was helpful, but I needed it in Python. So, I created this code.
You can add it to your repo:
```
import requests


def get_tiny_url(url_link):
    api_url = 'http://tinyurl.com/api-create.php?url=' + url_link
    response = requests.get(api_url)
    return response.text


if __name__ == '__main__':
    url = input('Enter the URL: ')
    new_url = get_tiny_url(url)
    if new_url != '':
        print(new_url)

```

**Comment by enishant** [comment]
> I was searching for an API, and I came across this. It was helpful, but I needed it in Python. So, I created this code. You can add it to your repo:
> 
> ```
> import requests
> 
> 
> def get_tiny_url(url_link):
>     api_url = 'http://tinyurl.com/api-create.php?url=' + url_link
>     response = requests.get(api_url)
>     return response.text
> 
> 
> if __name__ == '__main__':
>     url = input('Enter the URL: ')
>     new_url = get_tiny_url(url)
>     if new_url != '':
>         print(new_url)
> ```

@oriwideops This is old API call for url shortner, currently tinyurl is following new API with free/paid plans.
